language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_API}
  app: angelhack-anywehre-library

notifications:
  email:
    recipients:
      - cms3136@gmail.com